name: performance-checklist

on: 
  pull_request:
    types: [labeled]

jobs:
  comment-pr:
    if: ${{ github.event.label.name == 'performance sensitive' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment Performance Checklist on PR
        uses: actions/github-script@v6
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ github.event.pull_request.number }},
                body: 'Something'
              });
              console.log('comment added')
            } catch (error) {
              console.log(error)
              console.log('comment adding failed')
            }
